import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | Cloudie Kitchen bd",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h3>jh</h3>
    </div>
  );
}
